service: ometan
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs14.x
  profile: ome
  region: ap-northeast-1
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
package:
   individually: true
   include:
     - src/app/**
functions:
  slack:
    handler: src/app.handler
    events:
      - http:
          path: slack/events
          method: post
plugins:
  - serverless-plugin-typescript
  - serverless-offline
useDotenv: true
